// <auto-generated />
using System;
using IssuesApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IssuesApi.Migrations
{
    [DbContext(typeof(IssuesDataContext))]
    [Migration("20240227185259_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssuesApi.Services.SoftwareItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateRetired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RetirementNotificationsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoftwareCatalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8454e3c-406c-43f8-9c94-2cc4ab639487"),
                            DateAdded = new DateTimeOffset(new DateTime(2024, 2, 27, 13, 52, 59, 147, DateTimeKind.Unspecified).AddTicks(9385), new TimeSpan(0, -5, 0, 0, 0)),
                            RetirementNotificationsSent = false,
                            Title = "Microsoft Word",
                            Version = "97"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
